[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
via_ir = true
optimizer = true
optimizer_runs = 200
solc_version = "0.8.24"

[dependencies]
forge-std = "^1.7.0"
openzeppelin-contracts = "^5.0.0"
v4-core = { git = "https://github.com/Uniswap/v4-core", rev = "main" }
v4-periphery = { git = "https://github.com/Uniswap/v4-periphery", rev = "main" }
fhenix-contracts = { git = "https://github.com/FhenixProtocol/fhenix-contracts", rev = "main" }
cofhe-contracts = { git = "https://github.com/FhenixProtocol/cofhe-contracts", rev = "main" }
cofhe-mock-contracts = { git = "https://github.com/FhenixProtocol/cofhe-mock-contracts", rev = "main" }

[profile.ci]
fuzz = { runs = 10_000 }
invariant = { runs = 1_000 }

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 100
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[doc]
out = "docs"
title = "FHEAP - FHE Arbitrage Protection"