[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
via_ir = true
optimizer = true
optimizer_runs = 200
solc_version = "0.8.24"

[rpc_endpoints]
local = "http://localhost:8545"
helium = "https://api.helium.fhenix.zone"
fhenix = "https://api.fhenix.zone"

[etherscan]
helium = { key = "${HELIUM_ETHERSCAN_API_KEY}" }
fhenix = { key = "${FHENIX_ETHERSCAN_API_KEY}" }

[profile.ci]
fuzz = { runs = 10_000 }
invariant = { runs = 1_000 }

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 100
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[doc]
out = "docs"
title = "FHEAP - FHE Arbitrage Protection"